[package]
name = "rust_doc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "*"
serde = "*"
serde_json = "*"
serde_yaml = "*"
zvariant = "*"
zbus = "*"
rtnetlink = "*"
netlink-packet-route = "*"
futures = "*"
mio = "*"
ipnet = "*"
dhcproto = "*"
slint = "*"
regex = "*"
chrono = "*"
etherparse = "*"
smol = "*"
syslog = "*"
clap = { version = "4.4.6", features = ["cargo", "debug", "derive", "env", "string", "unicode", "unstable-doc", "unstable-v5", "unstable-styles", "wrap_help"] }
nix = { version = "0.27.1", features = ["fs", "hostname", "ioctl", "net", "poll", "time", "term", "uio", "user", "zerocopy"] }
tokio = { version = "1.33.0", features = ["full"] }
libc = "0.2.149"
uuid = { version = "1.5.0", features = ["v4", "v5", "v6", "v7", "v8", "rand", "serde", "zerocopy"] }
ethtool = "*"
